language: python

python: 3.6.5

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0 PIPENV_NOSPIN=true

before_install:
  - docker --version && docker-compose --version

install:
  - pip install pipenv
  - pipenv --bare install --deploy --ignore-pipfile --dev

script:
  - pipenv run python -m pytest
  - sh tests/test_integration.sh
  - pipenv check  # check local deps security

notifications:
  email:
    on_success: never
    on_failure: change
