language: python

python: 3.6.6

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  - PIPENV_NOSPIN=true

install:
  - pip install -U docker-compose pipenv
  - docker --version && docker-compose --version
  - pipenv --bare install --deploy --ignore-pipfile --dev

script:
  - pipenv run python -m pytest
  - sh tests/test_integration.sh
  - pipenv check

notifications:
  email:
    on_success: never
    on_failure: change
