language: python

python: 3.6

services:
  - docker

env:
  - PIPENV_SHELL_COMPAT=true PIPENV_COLORBLIND=true PIPENV_NOSPIN=true

install:
  - pip install pipenv
  - pipenv --bare install --ignore-pipfile --dev

script:
  - pipenv run python -m pytest
  - sh tests/test_integration.sh
  - pipenv check  # check local deps security

notifications:
  email:
    on_success: never
    on_failure: change
