dist: xenial
language: python

python: 3.7

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  - POETRY_VERSION=1.0.0

install:
  - pip freeze | xargs pip uninstall -y
  - pip install -U docker-compose docker-image-size-limit
  - curl -sSL "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python
  - source "$HOME/.poetry/env"
  - docker --version && docker-compose --version && poetry --version
  - poetry install

script:
  - flake8 .
  - pytest
  - sh tests/test_integration.sh
  - poetry check
  - poetry run safety check --bare --full-report

notifications:
  email:
    on_success: never
    on_failure: change
