---
{% if cookiecutter.docker == 'y' %}
- repo: local
  hooks:
    - id: qa
      name: qa
      entry: docker-compose run -e INSIDE_CI=0 web sh ./docker/ci.sh
      pass_filenames: false
      language: system
{% else %}- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: pytest
      pass_filenames: false
      language: python

    - id: mypy
      name: mypy
      entry: mypy server
      pass_filenames: false
      language: python

    - id: qa
      name: qa with radon
      entry: xenon --max-absolute B --max-modules A --max-average A .
      pass_filenames: false
      language: python

    - id: pipenv-check
      name: pipenv-check safety and pep508 check
      entry: pipenv check
      pass_filenames: false
      language: python
{% endif %}
