version: "3"
services:
  caddy:
    image: "wemakeservices/caddy-docker:latest"
    env_file: ./config/.env
    volumes:
      - ./docker/caddy/Caddyfile:/root/.caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
    depends_on:
      - web
    networks:
      - webnet

  web:
    image: "registry.gitlab.com/{{ cookiecutter.organization }}/{{ cookiecutter.project_name }}:latest"
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: production
    command: sh ./docker/django/gunicorn.sh
    environment:
      DJANGO_ENV: production
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
