version: "3"
services:
  caddy:
    image: "wemakeservices/caddy-docker:latest"
    env_file: ./config/.env
    volumes:
      - ./docker/caddy/Caddyfile:/root/.caddy/Caddyfile
    ports:
      - "2015:2015"
      - "8080:80"
      - "4430:443"
    depends_on:
      - web

  web:
    image: "registry.gitlab.com/{{ cookiecutter.organization }}/{{ cookiecutter.project_name }}:latest"
    build:
      # Default DJANGO_ENV for Dockerfile is `production`
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: ./docker/django/gunicorn.sh
    ports:
      - "5000:5000"
    environment:
      DJANGO_DATABASE_HOST: db
